amazon:
 associateId: loloara-20
---
spring:
 profiles: development
 thymeleaf:
  cache: false

server:
 port: 80

logging:
 level:
  root: DEBUG
---
spring:
 profiles: production

server:
 port: 8443
 ssl:
  enabled: true
  key-store: keystore.p12
  key-store-password: letmein
  key-password: letmein
  key-store-type: PKCS12
  key-alias: bns-ssl

logging:
 path: /logs/
 file: app.log
 level:
  root: WARN